/**
 *
 * @author Nasir Basha K
 */
import java.awt.Color;
import java.lang.String;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

public class Calc extends javax.swing.JFrame {

    
    String inFix;
    String postFix;
    String stack[]= new String[50];
    int top = -1;
   
    public Calc() {
        initComponents();
        RadoOn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        button1 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        TxtDisplay = new javax.swing.JTextField();
        BtnMinus = new javax.swing.JButton();
        BtnModulo = new javax.swing.JButton();
        BtnClr = new javax.swing.JButton();
        BtnPower = new javax.swing.JButton();
        BtnZero = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        BtnDot = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        BtnDivide = new javax.swing.JButton();
        BtnEquals = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        BtnMultiply = new javax.swing.JButton();
        BtnPlus = new javax.swing.JButton();
        BtnDel = new javax.swing.JButton();
        BtnOpen = new javax.swing.JButton();
        BtnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        TxtTest = new javax.swing.JTextField();
        TxtTest1 = new javax.swing.JTextField();
        RadoOn = new javax.swing.JRadioButton();
        RadoOff = new javax.swing.JRadioButton();

        button1.setLabel("button1");

        jLabel2.setText("jLabel2");

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nasir Basha K");
        setSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtDisplay.setEditable(false);
        TxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(TxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, -1));

        BtnMinus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnMinus.setText("-");
        BtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 60, 40));

        BtnModulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnModulo.setText("%");
        BtnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModuloActionPerformed(evt);
            }
        });
        getContentPane().add(BtnModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 70, 40));

        BtnClr.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnClr.setText("clr");
        BtnClr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClrActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 40));

        BtnPower.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnPower.setText("^");
        BtnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPowerActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 60, 40));

        BtnZero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnZero.setText("0");
        BtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnZeroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 70, 40));

        Btn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, 40));

        BtnDot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnDot.setText(".");
        getContentPane().add(BtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 70, 40));

        Btn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 70, 40));

        Btn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 40));

        Btn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 70, 40));

        Btn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 70, 40));

        Btn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 40));

        Btn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 70, 40));

        Btn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 40));

        BtnDivide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnDivide.setText("/");
        BtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivideActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 60, 40));

        BtnEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnEquals.setText("=");
        BtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 130, 40));

        Btn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 40));

        BtnMultiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnMultiply.setText("*");
        BtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplyActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 60, 40));

        BtnPlus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnPlus.setText("+");
        BtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 60, 40));

        BtnDel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnDel.setText("del");
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 40));

        BtnOpen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnOpen.setText("(");
        BtnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOpenActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 40));

        BtnClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnClose.setText(")");
        BtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(BtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("         Calc");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 200, -1));

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton23.setText("off");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 40));

        TxtTest.setEditable(false);
        TxtTest.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(TxtTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 300, -1));

        TxtTest1.setEditable(false);
        TxtTest1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(TxtTest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 300, 30));

        buttonGroup1.add(RadoOn);
        RadoOn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RadoOn.setText("ON");
        RadoOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadoOnActionPerformed(evt);
            }
        });
        getContentPane().add(RadoOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        buttonGroup1.add(RadoOff);
        RadoOff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RadoOff.setText("OFF");
        RadoOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadoOffActionPerformed(evt);
            }
        });
        getContentPane().add(RadoOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        setSize(new java.awt.Dimension(342, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void push(String a){
        stack[++top]=a;
    }
    
    private String pop(){
        return  stack[top --];
    }
    
    private int stackPriority(String ch){
        switch(ch){
            case "#":
            case "(":return 0;
            case "+":
            case "-":return 2;
            case "*":
            case "/":
            case "%":return 4;
            case "^":return 5;
        }
        return 0;
    }
    
    private int inputPriority(String ch){
        switch(ch){
            
         
            case "+":
            case "-":return 1;
            case "*":
            case "/":
            case "%":return 3;
            case "^":return 6;
        }
        return 0;
    }
    
    private void convert(){
        int j=0;
        char ch;
        for(int i=0;i < inFix.length();i++){
            ch=inFix.charAt(i);
            switch(Character.toString(ch)){
                case "(": push(Character.toString(ch));
                           break;
                case ")":
                    try{
                      while(!stack[top].contentEquals("(")){
                        if(postFix == null){
                            postFix = pop();
                        }
                        else{
                        postFix  = postFix + pop();
                        }
                    }}catch(Exception e){
                        
                    }
                    pop();
                         break;
                case "+":
                case "-":
                case "*":
                case "/":
                case "%":
                case "^":
                    try{
                    while(stackPriority( stack[top]) > inputPriority(Character.toString(ch))){
                        postFix = postFix + pop();
                    }}catch(Exception e){
                        
                    }
                    push(Character.toString(ch));
                        break;
                default:postFix = postFix + ch;
            }
            
        }
        try{
      while(!stack[top].contentEquals("#")){
            postFix = postFix + pop();
        }}catch(Exception e){
            
        }
        postFix=postFix.substring(4);
        
    }
    
     private void evaluate(){
        char ch;
        String a ,b;
        for(int i=0;i< postFix.length();i++){
            ch=postFix.charAt(i);
            if(Character.isDigit(ch)){
                push(Character.toString(ch));
            }
                else{
                         b=pop();
                     int b1= Integer.parseInt(b);
                          a=pop();
                     int a1= Integer.parseInt(a);
                        
                        switch(ch){
                            case '+':
                                push(Integer.toString(a1+b1));
                                    break;
                            case '-':
                                push(Integer.toString(a1-b1));
                                    break;
                            case '*':
                                push(Integer.toString(a1*b1));
                                    break;
                            case '/':
                                    if(b1 != 0)
                                push(Integer.toString(a1/b1));
                                    break;
                            case '^':
                                push(Integer.toString((int) Math.pow(a1,b1)));
                                    break;
                            
                        }
                        
                        }
            
        }
    }
    
    
    
    
    
    private void BtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEqualsActionPerformed
        try{
            push("#");
        convert();
        evaluate();
        }catch(Exception e){
            
            TxtDisplay.setText("cannot be converted");
             inFix=null;
            postFix=null;
           
        }
        /*if(pop().contentEquals("#")){
            TxtDisplay.setBackground(Color.red); 
            TxtDisplay.setText("Syntax Error");
            TxtTest.setText("Syntax Error");
            TxtTest1.setText("Syntax Error");
        }
        else{*/
        TxtDisplay.setBackground(Color.green);
        TxtDisplay.setText(pop());
         TxtTest.setBackground(Color.ORANGE);
        TxtTest.setText(inFix);
        TxtTest1.setText(postFix);
        inFix=null;
        postFix=null;
       // }
    }//GEN-LAST:event_BtnEqualsActionPerformed

    
    
    private void BtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPlusActionPerformed
        
          String s="+";
      
       if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_BtnPlusActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
       
          String s="7";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
        
    }//GEN-LAST:event_Btn7ActionPerformed

    private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
      
         String s=")";
      
       if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
        
        
    }//GEN-LAST:event_BtnCloseActionPerformed

    private void BtnClrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClrActionPerformed
        inFix=null;
        postFix=null;
        TxtDisplay.setText(inFix);
        TxtTest.setText(inFix);
         TxtTest1.setText(postFix);
        
        
    }//GEN-LAST:event_BtnClrActionPerformed

    private void BtnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOpenActionPerformed
       String s="(";
       
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_BtnOpenActionPerformed

    private void BtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnZeroActionPerformed
       
          String s="0";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
    }//GEN-LAST:event_BtnZeroActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        
          String s="1";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
       
          String s="2";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
        
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
         String s="3";
      
       if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
          String s="4";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        
          String s="5";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
       
          String s="6";
      
       if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        
          String s="8";
          
       if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
      
          String s="9";
      
       if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_Btn9ActionPerformed

    private void BtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusActionPerformed
       
          String s="-";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
        
    }//GEN-LAST:event_BtnMinusActionPerformed

    private void BtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplyActionPerformed
       
          String s="*";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
    }//GEN-LAST:event_BtnMultiplyActionPerformed

    private void BtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivideActionPerformed
        
          String s="/";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_BtnDivideActionPerformed

    private void BtnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPowerActionPerformed
       
          String s="^";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
    }//GEN-LAST:event_BtnPowerActionPerformed

    private void BtnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModuloActionPerformed
       
          String s="%";
      
        if(inFix == null){
           inFix = s;
            TxtDisplay.setText(inFix);
       } 
       else{
           inFix =inFix + s;
           TxtDisplay.setText(inFix);
       }
        
        
        
        
    }//GEN-LAST:event_BtnModuloActionPerformed

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
       
        if(inFix == null){
            TxtDisplay.setText("Nothing to Delet");
        }
        else{
        inFix=inFix.substring(0,inFix.length()-1);
        TxtDisplay.setText(inFix);
        }
    
        
    }//GEN-LAST:event_BtnDelActionPerformed

    private void TxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDisplayActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
      System.exit(0);
        
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void RadoOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadoOnActionPerformed
       RadoOff.setEnabled(true);
       RadoOn.setEnabled(false);
        Enable(true);
        
    }//GEN-LAST:event_RadoOnActionPerformed

   public void Enable(Boolean s){
       
       BtnZero.setEnabled(s);
       Btn1.setEnabled(s);
       Btn2.setEnabled(s);
       Btn3.setEnabled(s);
       Btn4.setEnabled(s);
       Btn5.setEnabled(s);
       Btn6.setEnabled(s);
       Btn7.setEnabled(s);
       Btn8.setEnabled(s);
       Btn9.setEnabled(s);
       BtnPlus.setEnabled(s);
       BtnMinus.setEnabled(s);
       BtnMultiply.setEnabled(s);
       BtnDivide.setEnabled(s);
       BtnModulo.setEnabled(s);
       BtnClose.setEnabled(s);
       BtnClr.setEnabled(s);
       BtnDel.setEnabled(s);
       BtnDot.setEnabled(s);
       BtnEquals.setEnabled(s);
       BtnOpen.setEnabled(s);
       BtnPower.setEnabled(s);
       TxtDisplay.setEnabled(s);
       TxtTest.setEnabled(s);
       TxtTest1.setEnabled(s);
   } 
   
    private void RadoOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadoOffActionPerformed
          RadoOn.setEnabled(true);
          RadoOff.setEnabled(false);
        Enable(false);
             
    }//GEN-LAST:event_RadoOffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
      
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnClose;
    private javax.swing.JButton BtnClr;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnDivide;
    private javax.swing.JButton BtnDot;
    private javax.swing.JButton BtnEquals;
    private javax.swing.JButton BtnMinus;
    private javax.swing.JButton BtnModulo;
    private javax.swing.JButton BtnMultiply;
    private javax.swing.JButton BtnOpen;
    private javax.swing.JButton BtnPlus;
    private javax.swing.JButton BtnPower;
    private javax.swing.JButton BtnZero;
    private javax.swing.JRadioButton RadoOff;
    private javax.swing.JRadioButton RadoOn;
    private javax.swing.JTextField TxtDisplay;
    private javax.swing.JTextField TxtTest;
    private javax.swing.JTextField TxtTest1;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
